
services:
  postgres:
    image: postgres:16-alpine
    container_name: systech-aidd-postgres
    environment:
      POSTGRES_DB: systech_aidd
      POSTGRES_USER: systech
      POSTGRES_PASSWORD: systech_dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U systech -d systech_aidd"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:


